class EventType:
    CASE_STARTED = "case_started"
    CASE_COMPLETED = "case_completed"
    EVIDENCE_COLLECTED = "evidence_collected"
    CONTRADICTION_FOUND = "contradiction_found"
    THEORY_SUBMITTED = "theory_submitted"
    XP_GAINED = "xp_gained"
    RANK_UP = "rank_up"
    ACHIEVEMENT_UNLOCKED = "achievement_unlocked"
    PURCHASE_MADE = "purchase_made"
    SAVE_REQUESTED = "save_requested"
    SAVE_COMPLETED = "save_completed"
    SETTINGS_CHANGED = "settings_changed"
    NOTIFICATION_REQUESTED = "notification_requested"
    STATE_CHANGED = "state_changed"
